# Generated by Django 2.2.1 on 2019-05-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('ano_inicio', models.IntegerField(default=2018)),
                ('ano_fim', models.IntegerField(default=2022)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
    ]
